#!/bin/bash
set -euo pipefail

printf "\n=====================================================================================\n"
printf "KOBITON APP UPLOAD PLUGIN"
printf "\n=====================================================================================\n\n"

../build/app

printf "\n=====================================================================================\n"
printf "Uploaded app to kobiton repo with appId: ${APP_ID} and versionId: ${APP_VERSION_ID}\n"
printf "Done."
printf "\n=====================================================================================\n"