#!/bin/bash
set -euo pipefail

printf "\n=====================================================================================\n"
printf "KOBITON APP UPLOAD PLUGIN"
printf "\n=====================================================================================\n\n"

EXECUTOR_URL="$BUILDKITE_PLUGIN_KOBITON_EXECUTE_TEST_EXECUTOR_URL"

printf "EXECUTOR_URL: $EXECUTOR_URL"

$BUILDKITE_PLUGINS_PATH/github-com-Nhattd97-kobiton-execute-test-buildkite-plugin-v1-0-0/build/app

printf "\n=====================================================================================\n"
printf "Uploaded app to kobiton repo with appId: ${APP_ID} and versionId: ${APP_VERSION_ID}\n"
printf "Done."
printf "\n=====================================================================================\n"
